var allbirds = {
  "RBGU" : { "name" : "Ring-billed Gull", "sciname" : "Larus delawarensis" },
  "WITU" : { "name" : "Wild Turkey", "sciname" : "Meleagris gallopavo" },
  "BARS" : { "name" : "Barn Swallow", "sciname" : "Hirundo rustica" },
  "RWBL" : { "name" : "Red-winged Blackbird", "sciname" : "Agelaius phoeniceus" },
  "HOSP" : { "name" : "House Sparrow", "sciname" : "Passer domesticus" },
  "SPTO" : { "name" : "Spotted Towhee", "sciname" : "Pipilo maculatus" },
  "CANG" : { "name" : "Canada Goose", "sciname" : "Branta canadensis" },
  "MAFR" : { "name" : "Magnificent Frigatebird", "sciname" : "Fregata magnificens" },
  "BUSH" : { "name" : "Bushtit", "sciname" : "Psaltriparus minimus" },
  "CANV" : { "name" : "Canvasback", "sciname" : "Aythya valisineria" },
  "EAGR" : { "name" : "Eared Grebe", "sciname" : "Podiceps nigricollis" },
  "CANT" : { "name" : "Canyon Towhee", "sciname" : "Melozone fusca" },
  "KILL" : { "name" : "Killdeer", "sciname" : "Charadrius vociferus" },
  "LESA" : { "name" : "Least Sandpiper", "sciname" : "Calidris minutilla" },
  "LESC" : { "name" : "Lesser Scaup", "sciname" : "Aythya affinis" },
  "TUVU" : { "name" : "Turkey Vulture", "sciname" : "Cathartes aura" },
  "CONI" : { "name" : "Common Nighthawk", "sciname" : "Chordeiles minor" },
  "GHOW" : { "name" : "Great Horned Owl", "sciname" : "Bubo virginianus" },
  "MUSW" : { "name" : "Mute Swan", "sciname" : "Cygnus olor" },
  "BRPE" : { "name" : "Brown Pelican", "sciname" : "Pelecanus occidentalis" },
  "LASP" : { "name" : "Lark Sparrow", "sciname" : "Chondestes grammacus" },
  "SEPL" : { "name" : "Semipalmated Plover", "sciname" : "Charadrius semipalmatus" },
  "VESP" : { "name" : "Vesper Sparrow", "sciname" : "Pooecetes gramineus" },
  "SSHA" : { "name" : "Sharp-shinned Hawk", "sciname" : "Accipiter striatus" },
  "OSPR" : { "name" : "Osprey", "sciname" : "Pandion haliaetus" },
  "SOSP" : { "name" : "Song Sparrow", "sciname" : "Melospiza melodia" },
  "SAND" : { "name" : "Sanderling", "sciname" : "Calidris alba" },
  "GRFL" : { "name" : "Gray Flycatcher", "sciname" : "Empidonax wrightii" },
  "NOHA" : { "name" : "Northern Harrier", "sciname" : "Circus cyaneus" },
  "RUHU" : { "name" : "Rufous Hummingbird", "sciname" : "Selasphorus rufus" },
  "GREG" : { "name" : "Great Egret", "sciname" : "Ardea alba" },
  "WTSP" : { "name" : "White-throated Sparrow", "sciname" : "Zonotrichia albicollis" },
  "HEEG" : { "name" : "Heermann's Gull", "sciname" : "Larus heermanni" },
  "DCCO" : { "name" : "Double-crested Cormorant", "sciname" : "Phalacrocorax auritus" },
  "HOFI" : { "name" : "House Finch", "sciname" : "Haemorhous mexicanus" },
  "BBMA" : { "name" : "Black-billed Magpie", "sciname" : "Pica hudsonia" },
  "ZTHA" : { "name" : "Zone-tailed Hawk", "sciname" : "Buteo albonotatus" },
  "BEWR" : { "name" : "Bewick's Wren", "sciname" : "Thryomanes bewickii" },
  "BEKI" : { "name" : "Belted Kingfisher", "sciname" : "Megaceryle alcyon" },
  "CBTH" : { "name" : "Curve-billed Thrasher", "sciname" : "Toxostoma curvirostre" },
  "AMRO" : { "name" : "American Robin", "sciname" : "Turdus migratorius" },
  "VIRA" : { "name" : "Virginia Rail", "sciname" : "Rallus limicola" },
  "GRRO" : { "name" : "Greater Roadrunner", "sciname" : "Geococcyx californianus" },
  "HAWO" : { "name" : "Hairy Woodpecker", "sciname" : "Picoides villosus" },
  "WISA" : { "name" : "Williamson's Sapsucker", "sciname" : "Sphyrapicus thyroideus" },
  "AMKE" : { "name" : "American Kestrel", "sciname" : "Falco sparverius" },
  "WTTR" : { "name" : "White-tailed Tropicbird", "sciname" : "Phaethon lepturus" },
  "GOEA" : { "name" : "Golden Eagle", "sciname" : "Aquila chrysaetos" },
  "PRAW" : { "name" : "Prairie Warbler", "sciname" : "Setophaga discolor" },
  "WEME" : { "name" : "Western Meadowlark", "sciname" : "Sturnella neglecta" },
  "CANW" : { "name" : "Canyon Wren", "sciname" : "Catherpes mexicanus" },
  "LEGO" : { "name" : "Lesser Goldfinch", "sciname" : "Spinus psaltria" },
  "SAVS" : { "name" : "Savannah Sparrow", "sciname" : "Passerculus sandwichensis" },
  "TOWA" : { "name" : "Townsend's Warbler", "sciname" : "Setophaga townsendi" },
  "AMCO" : { "name" : "American Coot", "sciname" : "Fulica americana" },
  "ORJU" : { "name" : "Oregon Junco", "sciname" : "Junco h. oregonus" },
  "PSJU" : { "name" : "Pink-sided Junco", "sciname" : "Junco h. mearnsi" },
  "SCOR" : { "name" : "Scott's Oriole", "sciname" : "Icterus parisorum" },
  "BUFF" : { "name" : "Bufflehead", "sciname" : "Bucephala albeola" },
  "OATI" : { "name" : "Oak Titmouse", "sciname" : "Baeolophus inornatus" },
  "LBCU" : { "name" : "Long-billed Curlew", "sciname" : "Numenius americanus" },
  "BCHU" : { "name" : "Black-chinned Hummingbird", "sciname" : "Archilochus alexandri" },
  "WREN" : { "name" : "Wrentit", "sciname" : "Chamaea fasciata" },
  "CAFI" : { "name" : "Cassin's Finch", "sciname" : "Haemorhous cassinii" },
  "DUGR" : { "name" : "Dusky Grouse", "sciname" : "Dendragapus obscurus" },
  "BLTU" : { "name" : "Black Turnstone", "sciname" : "Arenaria melanocephala" },
  "DOWO" : { "name" : "Downy Woodpecker", "sciname" : "Picoides pubescens" },
  "AMAV" : { "name" : "American Avocet", "sciname" : "Recurvirostra americana" },
  "GTGR" : { "name" : "Great-tailed Grackle", "sciname" : "Quiscalus mexicanus" },
  "DUFL" : { "name" : "Dusky Flycatcher", "sciname" : "Empidonax oberholseri" },
  "BLGR" : { "name" : "Blue Grosbeak", "sciname" : "Passerina caerulea" },
  "BLTE" : { "name" : "Black Tern", "sciname" : "Chlidonias niger" },
  "WILL" : { "name" : "Willet", "sciname" : "Tringa semipalmata" },
  "RNPH" : { "name" : "Red-necked Phalarope", "sciname" : "Phalaropus lobatus" },
  "GBHE" : { "name" : "Great Blue Heron", "sciname" : "Ardea herodias" },
  "VIWA" : { "name" : "Virginia's Warbler", "sciname" : "Oreothlypis virginiae" },
  "VGSW" : { "name" : "Violet-green Swallow", "sciname" : "Tachycineta thalassina" },
  "LEYE" : { "name" : "Lesser Yellowlegs", "sciname" : "Tringa flavipes" },
  "MALL" : { "name" : "Mallard", "sciname" : "Anas platyrhynchos" },
  "NOFL" : { "name" : "Northern Flicker", "sciname" : "Colaptes auratus" },
  "BRTH" : { "name" : "Brown Thrasher", "sciname" : "Toxostoma rufum" },
  "RFBO" : { "name" : "Red-footed Booby", "sciname" : "Sula sula" },
  "RTTR" : { "name" : "Red-tailed Tropicbird", "sciname" : "Phaethon rubricauda" },
  "WEGR" : { "name" : "Western Grebe", "sciname" : "Aechmophorus occidentalis" },
  "WEGU" : { "name" : "Western Gull", "sciname" : "Larus occidentalis" },
  "HETH" : { "name" : "Hermit Thrush", "sciname" : "Catharus guttatus" },
  "CAGU" : { "name" : "California Gull", "sciname" : "Larus californicus" },
  "RHWO" : { "name" : "Red-headed Woodpecker", "sciname" : "Melanerpes erythrocephalus" },
  "PYNU" : { "name" : "Pygmy Nuthatch", "sciname" : "Sitta pygmaea" },
  "MAGO" : { "name" : "Marbled Godwit", "sciname" : "Limosa fedoa" },
  "PEFA" : { "name" : "Peregrine Falcon", "sciname" : "Falco peregrinus" },
  "CLNU" : { "name" : "Clark's Nutcracker", "sciname" : "Nucifraga columbiana" },
  "LAZB" : { "name" : "Lazuli Bunting", "sciname" : "Passerina amoena" },
  "ANHU" : { "name" : "Anna's Hummingbird", "sciname" : "Calypte anna" },
  "BTYW" : { "name" : "Black-throated Gray Warbler", "sciname" : "Setophaga nigrescens" },
  "MGWA" : { "name" : "MacGillivray's Warbler", "sciname" : "Geothlypis tolmiei" },
  "CAHU" : { "name" : "Calliope Hummingbird", "sciname" : "Selasphorus calliope" },
  "STJA" : { "name" : "Steller's Jay", "sciname" : "Cyanocitta stelleri" },
  "AMPI" : { "name" : "American Pipit", "sciname" : "Anthus rubescens" },
  "SAPH" : { "name" : "Say's Phoebe", "sciname" : "Sayornis saya" },
  "WTKI" : { "name" : "White-tailed Kite", "sciname" : "Elanus leucurus" },
  "PIJA" : { "name" : "Pinyon Jay", "sciname" : "Gymnorhinus cyanocephalus" },
  "GCSP" : { "name" : "Golden-crowned Sparrow", "sciname" : "Zonotrichia atricapilla" },
  "BTAH" : { "name" : "Broad-tailed Hummingbird", "sciname" : "Selasphorus platycercus" },
  "PLVI" : { "name" : "Plumbeous Vireo", "sciname" : "Vireo plumbeus" },
  "BLOY" : { "name" : "Black Oystercatcher", "sciname" : "Haematopus bachmani" },
  "NOPI" : { "name" : "Northern Pintail", "sciname" : "Anas acuta" },
  "YEWA" : { "name" : "Yellow Warbler", "sciname" : "Setophaga petechia" },
  "NOGO" : { "name" : "Northern Goshawk", "sciname" : "Accipiter gentilis" },
  "EAME" : { "name" : "Eastern Meadowlark", "sciname" : "Sturnella magna" },
  "BAEA" : { "name" : "Bald Eagle", "sciname" : "Haliaeetus leucocephalus" },
  "NOPO" : { "name" : "Northern Pygmy-Owl", "sciname" : "Glaucidium gnoma" },
  "BOGU" : { "name" : "Bonaparte's Gull", "sciname" : "Chroicocephalus philadelphia" },
  "COSA" : { "name" : "Common Sandpiper", "sciname" : "Actitis hypoleucos" },
  "YBMA" : { "name" : "Yellow-billed Magpie", "sciname" : "Pica nuttalli" },
  "AMGO" : { "name" : "American Goldfinch", "sciname" : "Spinus tristis" },
  "WEBL" : { "name" : "Western Bluebird", "sciname" : "Sialia mexicana" },
  "BCNH" : { "name" : "Black-crowned Night-Heron", "sciname" : "Nycticorax nycticorax" },
  "WIPH" : { "name" : "Wilson's Phalarope", "sciname" : "Phalaropus tricolor" },
  "JUTI" : { "name" : "Juniper Titmouse", "sciname" : "Baeolophus ridgwayi" },
  "MERL" : { "name" : "Merlin", "sciname" : "Falco columbarius" },
  "SACR" : { "name" : "Sandhill Crane", "sciname" : "Grus canadensis" },
  "HOME" : { "name" : "Hooded Merganser", "sciname" : "Lophodytes cucullatus" },
  "WWDO" : { "name" : "White-winged Dove", "sciname" : "Zenaida asiatica" },
  "EASO" : { "name" : "Eastern Screech-Owl", "sciname" : "Megascops asio" },
  "COCU" : { "name" : "Common Cuckoo", "sciname" : "Cuculus canorus" },
  "GRYE" : { "name" : "Greater Yellowlegs", "sciname" : "Tringa melanoleuca" },
  "MOBL" : { "name" : "Mountain Bluebird", "sciname" : "Sialia currucoides" },
  "PYRR" : { "name" : "Pyrrhuloxia", "sciname" : "Cardinalis sinuatus" },
  "RSHA" : { "name" : "Red-shouldered Hawk", "sciname" : "Buteo lineatus" },
  "WTSW" : { "name" : "White-throated Swift", "sciname" : "Aeronautes saxatalis" },
  "GRAJ" : { "name" : "Gray Jay", "sciname" : "Perisoreus canadensis" },
  "PBGR" : { "name" : "Pied-billed Grebe", "sciname" : "Podilymbus podiceps" },
  "COGO" : { "name" : "Common Goldeneye", "sciname" : "Bucephala clangula" },
  "CAQU" : { "name" : "California Quail", "sciname" : "Callipepla californica" },
  "SUSC" : { "name" : "Surf Scoter", "sciname" : "Melanitta perspicillata" },
  "GWFG" : { "name" : "Greater White-fronted Goose", "sciname" : "Anser albifrons" },
  "HASH" : { "name" : "Harris's Hawk", "sciname" : "Parabuteo unicinctus" },
  "CORA" : { "name" : "Common Raven", "sciname" : "Corvus corax" },
  "BGGN" : { "name" : "Blue-gray Gnatcatcher", "sciname" : "Polioptila caerulea" },
  "CLSW" : { "name" : "Cliff Swallow", "sciname" : "Petrochelidon pyrrhonota" },
  "FOTE" : { "name" : "Forster's Tern", "sciname" : "Sterna forsteri" },
  "HERG" : { "name" : "Herring Gull", "sciname" : "Larus argentatus" },
  "ACWO" : { "name" : "Acorn Woodpecker", "sciname" : "Melanerpes formicivorus" },
  "LEWO" : { "name" : "Lewis's Woodpecker", "sciname" : "Melanerpes lewis" },
  "BHGR" : { "name" : "Black-headed Grosbeak", "sciname" : "Pheucticus melanocephalus" },
  "OCWA" : { "name" : "Orange-crowned Warbler", "sciname" : "Oreothlypis celata" },
  "TOSO" : { "name" : "Townsend's Solitaire", "sciname" : "Myadestes townsendi" },
  "COMO" : { "name" : "Common Moorhen", "sciname" : "Gallinula chloropus" },
  "COME" : { "name" : "Common Merganser", "sciname" : "Mergus merganser" },
  "WODU" : { "name" : "Wood Duck", "sciname" : "Aix sponsa" },
  "ROWR" : { "name" : "Rock Wren", "sciname" : "Salpinctes obsoletus" },
  "ROPI" : { "name" : "Rock Pigeon", "sciname" : "Columba livia" },
  "SNEG" : { "name" : "Snowy Egret", "sciname" : "Egretta thula" },
  "EUCD" : { "name" : "Eurasian Collared-Dove", "sciname" : "Streptopelia decaocto" },
  "CBCH" : { "name" : "Chestnut-backed Chickadee", "sciname" : "Poecile rufescens" },
  "NOMO" : { "name" : "Northern Mockingbird", "sciname" : "Mimus polyglottos" },
  "RNSA" : { "name" : "Red-naped Sapsucker", "sciname" : "Sphyrapicus nuchalis" },
  "BLSK" : { "name" : "Black Skimmer", "sciname" : "Rynchops niger" },
  "CHRA" : { "name" : "Chihuahuan Raven", "sciname" : "Corvus cryptoleucus" },
  "AUWA" : { "name" : "Audubon's Warbler", "sciname" : "Setophaga coronata auduboni" },
  "GADW" : { "name" : "Gadwall", "sciname" : "Anas strepera" },
  "ATFL" : { "name" : "Ash-throated Flycatcher", "sciname" : "Myiarchus cinerascens" },
  "NAWA" : { "name" : "Nashville Warbler", "sciname" : "Oreothlypis ruficapilla" },
  "HOOR" : { "name" : "Hooded Oriole", "sciname" : "Icterus cucullatus" },
  "CALT" : { "name" : "California Towhee", "sciname" : "Melozone crissalis" },
  "COHA" : { "name" : "Cooper's Hawk", "sciname" : "Accipiter cooperii" },
  "GTTO" : { "name" : "Green-tailed Towhee", "sciname" : "Pipilo chlorurus" },
  "SNOW" : { "name" : "Snowy Owl", "sciname" : "Bubo scandiacus" },
  "HOGR" : { "name" : "Horned Grebe", "sciname" : "Podiceps auritus" },
  "WHIM" : { "name" : "Whimbrel", "sciname" : "Numenius phaeopus" },
  "GRSC" : { "name" : "Greater Scaup", "sciname" : "Aythya marila" },
  "GRHE" : { "name" : "Green Heron", "sciname" : "Butorides virescens" },
  "HAFL" : { "name" : "Hammond's Flycatcher", "sciname" : "Empidonax hammondii" },
  "COYE" : { "name" : "Common Yellowthroat", "sciname" : "Geothlypis trichas" },
  "DEJU" : { "name" : "Dark-eyed Junco", "sciname" : "Junco hyemalis" },
  "WAVI" : { "name" : "Warbling Vireo", "sciname" : "Vireo gilvus" },
  "BLPH" : { "name" : "Black Phoebe", "sciname" : "Sayornis nigricans" },
  "BUOW" : { "name" : "Burrowing Owl", "sciname" : "Athene cunicularia" },
  "YHBL" : { "name" : "Yellow-headed Blackbird", "sciname" : "Xanthocephalus xanthocephalus" },
  "DUNL" : { "name" : "Dunlin", "sciname" : "Calidris alpina" },
  "SCQU" : { "name" : "Scaled Quail", "sciname" : "Callipepla squamata" },
  "EVGR" : { "name" : "Evening Grosbeak", "sciname" : "Coccothraustes vespertinus" },
  "BHCO" : { "name" : "Brown-headed Cowbird", "sciname" : "Molothrus ater" },
  "BRBL" : { "name" : "Brewer's Blackbird", "sciname" : "Euphagus cyanocephalus" },
  "CEDW" : { "name" : "Cedar Waxwing", "sciname" : "Bombycilla cedorum" },
  "NUWO" : { "name" : "Nuttall's Woodpecker", "sciname" : "Picoides nuttallii" },
  "WETA" : { "name" : "Western Tanager", "sciname" : "Piranga ludoviciana" },
  "BTSP" : { "name" : "Black-throated Sparrow", "sciname" : "Amphispiza bilineata" },
  "MODO" : { "name" : "Mourning Dove", "sciname" : "Zenaida macroura" },
  "WBNU" : { "name" : "White-breasted Nuthatch", "sciname" : "Sitta carolinensis" },
  "HOWR" : { "name" : "House Wren", "sciname" : "Troglodytes aedon" },
  "CACW" : { "name" : "Cactus Wren", "sciname" : "Campylorhynchus brunneicapillus" },
  "AWPE" : { "name" : "American White Pelican", "sciname" : "Pelecanus erythrorhynchos" },
  "WFIB" : { "name" : "White-faced Ibis", "sciname" : "Plegadis chihi" },
  "AMDI" : { "name" : "American Dipper", "sciname" : "Cinclus mexicanus" },
  "COMU" : { "name" : "Common Murre", "sciname" : "Uria aalge" },
  "WESJ" : { "name" : "Western Scrub-Jay", "sciname" : "Aphelocoma californica" },
  "YBLO" : { "name" : "Yellow-billed Loon", "sciname" : "Gavia adamsii" },
  "RTHA" : { "name" : "Red-tailed Hawk", "sciname" : "Buteo jamaicensis" },
  "CACG" : { "name" : "Cackling Goose", "sciname" : "Branta hutchinsii" },
  "RUDU" : { "name" : "Ruddy Duck", "sciname" : "Oxyura jamaicensis" },
  "WCSP" : { "name" : "White-crowned Sparrow", "sciname" : "Zonotrichia leucophrys" },
  "CHSP" : { "name" : "Chipping Sparrow", "sciname" : "Spizella passerina" },
  "HUGO" : { "name" : "Hudsonian Godwit", "sciname" : "Limosa haemastica" },
  "HOLA" : { "name" : "Horned Lark", "sciname" : "Eremophila alpestris" },
  "NSHO" : { "name" : "Northern Shoveler", "sciname" : "Anas clypeata" },
  "PISI" : { "name" : "Pine Siskin", "sciname" : "Spinus pinus" },
  "LBWO" : { "name" : "Ladder-backed Woodpecker", "sciname" : "Picoides scalaris" },
  "CATE" : { "name" : "Caspian Tern", "sciname" : "Hydroprogne caspia" },
  "RUTU" : { "name" : "Ruddy Turnstone", "sciname" : "Arenaria interpres" },
  "YRWA" : { "name" : "Yellow-rumped Warbler", "sciname" : "Setophaga coronata" },
  "CATH" : { "name" : "California Thrasher", "sciname" : "Toxostoma redivivum" },
  "WOSJ" : { "name" : "Woodhouse's Scrub-Jay", "sciname" : "Aphelocoma woodhouseii" },
  "RBNU" : { "name" : "Red-breasted Nuthatch", "sciname" : "Sitta canadensis" },
  "WEKI" : { "name" : "Western Kingbird", "sciname" : "Tyrannus verticalis" },
  "SNGO" : { "name" : "Snow Goose", "sciname" : "Chen caerulescens" },
  "MOCH" : { "name" : "Mountain Chickadee", "sciname" : "Poecile gambeli" },
  "REPH" : { "name" : "Red Phalarope", "sciname" : "Phalaropus fulicarius" },
  "BNST" : { "name" : "Black-necked Stilt", "sciname" : "Himantopus mexicanus" },
  "WESO" : { "name" : "Western Screech-Owl", "sciname" : "Megascops kennicottii" },
  "RNEP" : { "name" : "Ring-necked Pheasant", "sciname" : "Phasianus colchicus" },
  "BUOR" : { "name" : "Bullock's Oriole", "sciname" : "Icterus bullockii" },
  "RCKI" : { "name" : "Ruby-crowned Kinglet", "sciname" : "Regulus calendula" },
  "GWTE" : { "name" : "Green-winged Teal", "sciname" : "Anas crecca" },
  "SATH" : { "name" : "Sage Thrasher", "sciname" : "Oreoscoptes montanus" },
  "CITE" : { "name" : "Cinnamon Teal", "sciname" : "Anas cyanoptera" },
  "AMCR" : { "name" : "American Crow", "sciname" : "Corvus brachyrhynchos" },
  "BBHU" : { "name" : "Broad-billed Hummingbird", "sciname" : "Cynanthus latirostris" },
  "BASA" : { "name" : "Baird's Sandpiper", "sciname" : "Calidris bairdii" },
  "ANHI" : { "name" : "Anhinga", "sciname" : "Anhinga anhinga" },
  "NOCA" : { "name" : "Northern Cardinal", "sciname" : "Cardinalis cardinalis" },
  "PARE" : { "name" : "Painted Redstart", "sciname" : "Myioborus pictus" },
  "LAZB" : { "name" : "Lazuli Bunting", "sciname" : "Passerina amoena" },
  "LISP" : { "name" : "Lincoln's Sparrow", "sciname" : "Melospiza lincolnii" },
  "EAGR" : { "name" : "Eared Grebe", "sciname" : "Podiceps nigricollis" },
  "GIWO" : { "name" : "Gila Woodpecker", "sciname" : "Melanerpes uropygialis" },
  "COHU" : { "name" : "Costa's Hummingbird", "sciname" : "Calypte costae" },
};

