
var copyrights = {
  "images/akk" : "Image copyright Akkana Peck, CC-BY-SA",
  "images/yeamans" : "Image copyright David Yeamans",
  "images/wikicommons/Graces_warbler.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Grace's_Warbler.jpg\">dominic sherony on Wikimedia Commons</a>",
  "images/wikicommons/Lazuli_Bunting.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Lazuli_Bunting.jpg\">www.naturespicsonline.com on Wikimedia Commons</a>",
  "images/wikicommons/Lewis_s_woodpecker.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Lewis's_Woodpecker.jpg\">www.naturespicsonline.com via Wikimedia Commons</a>",
  "images/wikicommons/MacGillivrays_warbler.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Geothlypis_tolmiei_Hungry_Horse_MT_2.jpg\">Caleb Putnam on Wikimedia Commons</a>",
  "images/wikicommons/Virginia_rail.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Rallus_limicola_-Cloisters_Park,_Morro_Bay,_California,_USA-8.jpg\">Mike Baird on Wikimedia Commons</a>",
  "images/wikicommons/Virginias_warbler.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Female_Virgina's_Warbler.JPG\">Sabine's Sunbird on Wikimedia Commons</a>",
  "images/wikicommons/Williamsons_sapsucker.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Williamson's_Sapsucker_%289068046051%29.jpg\">Eleanor Briccetti on Wikimedia Commons</a>",
  "images/wikicommons/black-throated_gray_warbler.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Dendroica_nigrescens_on_rock.jpg\">Bigdeazy on Wikimedia Commons</a>",
  "images/wikicommons/blue-gray_gnatcatcher.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Polioptila_caerulea.jpg\">Elaine R. Wilson, NaturesPicsOnline on Wikimedia Commons</a>",
  "images/wikicommons/blue_grosbeak.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Blue_Grosbeak_male_RWD.jpg\">DickDaniels (http://carolinabirds.org/) via Wikimedia Commons</a>",
  "images/wikicommons/brown_creeper.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Brown_Creeper_%2813392257004%29.jpg\">Andy Reago & Chrissy McClarren on Wikimedia Commons</a>",
  "images/wikicommons/canyon_wren.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Canyon_Wren_%2818565207405%29.jpg\">Don Faulkner on Wikimedia Commons</a>",
  "images/wikicommons/common_nighthawk.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Chordeiles_minorEJN31CB.jpg\"><i>Fifty Birds of Town and City</i> via Wikimedia Commons</a>",
  "images/wikicommons/dusky_grouse.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Dendragapus_obscurus_NPS.jpg\">S. King, US NPS, on Wikimedia Commons</a>",
  "images/wikicommons/ladder-backed_woodpecker.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Ladder-backed_Woodpecker_%28female%29_%2826367753172%29.jpg\">Don Faulkner on Wikimedia Commons</a>",
  "images/wikicommons/merlin.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Falco_columbarius_%28Merlin%29_%285530094753%29.jpg\">David St. Louis on Wikimedia Commons</a>",
  "images/wikicommons/northern_goshawk.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Northern_Goshawk_ad_M2.jpg\">Norbert Kenntner on Wikimedia Commons</a>",
  "images/wikicommons/northern_pygmy-owl.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Mountain_Pygmy_Owl_Glaucidium_gnoma_Arizona.jpg\">dominic sherony on Wikimedia Commons</a>",
  "images/wikicommons/orange-crowned_warbler.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Vermivora_celata_lutescens_1.jpg\">Greg7 on Flickr via Wikimedia Commons</a>",
  "images/wikicommons/peregrine_falcon.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Falco_peregrinus_-Morro_Rock,_Morro_Bay,_California,_USA_-flying-8.jpg\">Mike Baird on Wikimedia Commons</a>",
  "images/wikicommons/pygmy_nuthatch.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Pygmy_Nuthatch_%28Sitta_pygmaea%29_%2820162655750%29.jpg\">Ron Knight on Wikimedia Commons</a>",
  "images/wikicommons/red-breasted_nuthatch.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Sitta_canadensis_CT2.jpg\">Cephas on Wikimedia Commons</a>",
  "images/wikicommons/red-naped_sapsucker.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Red-naped_sapsucker_sphyrapicus_nuchalis_cropped.JPG\">Kati Fleming on Wikimedia Commons</a>",
  "images/wikicommons/rock_wren.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Salpinctes_obsoletus_NPS.jpg\">S. King, US NPS on Wikimedia Commons</a>",
  "images/wikicommons/sharp-shinned_hawk.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Sharp-shinned_Hawk_looking_over_shoulder.jpg\">U.S. Fish and Wildlife Service Southeast Region on Wikimedia Commons</a>",
  "images/wikicommons/warbling_vireo.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:WarblingVireo08.jpg\">John Harrison at http://flickr.com/photos/15512543@N04/ via Wikimedia Commons</a>",
  "images/wikicommons/white-breasted_nuthatch.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:White-breasted_Nuthatch_RWD3.jpg\">DickDaniels (http://carolinabirds.org/) on Wikimedia Commons</a>",
  "images/wikicommons/yellow-headed_blackbird.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Yellowheadblackbird.jpg\">US Fish and Wildlife Service via Wikimedia Commons</a>",
  "images/wikicommons/yellow-rumped_warbler.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:Dendroica_coronata_CT.jpg\">Cephas on Wikimedia Commons</a>",
  "images/wikicommons/zone-tailed_hawk.jpg" : "Image from <a href=\"https://commons.wikimedia.org/wiki/File:ZonetailedHawk2.jpg\">Stolz, Gary M on Wikimedia Commons</a>",
  "sounds/SteveFettig" : "Image from Audio Copyright Steve Fettig",
};
